### ISSUE TITLE
Download PDF link does not work

### ISSUE THREAD

**Issue by WillAutioItrax** [syncfusion/xamarin-docs#6]
At this page:
https://help.syncfusion.com/xamarin/themes/keys
I am trying to use the "Download PDF" link but I get nothing.

**Comment by Gayathri-Sankarraj** [comment]
Hi @WillAutioItrax, 
  
Sorry for the inconvenience caused. The reported issue has been resolved and now the PDF file download is working fine in our documentation site. 
 
**Demo link**: [https://help.syncfusion.com/xamarin/themes/keys](https://help.syncfusion.com/xamarin/themes/keys) 

Regards,
Gayathri S.

**Comment by WillAutioItrax** [comment]
@Gayathri-Sankarraj  Awesome - thanks!
